### ISSUE TITLE
ng-repeat pagination not working

### ISSUE THREAD

**Issue by emiliano1616** [nebulr/ui-swiper#15]
When I use ng-repeat to create my slides, the pagination doesn't move fordward nor backward.
I'm not coping any code because this issue is even present in the demo page
[http://nebulr.github.io/ui-swiper/](url)

When I press on the next and prev buttons, the pagination works just fine. The problem is only with drag and drop.

I can only reproduce this error on chrome and in my phonegap application.

**Comment by Hyperblaster** [comment]
Same issue

**Comment by Hyperblaster** [comment]
Same issue

**Comment by Hyperblaster** [comment]
I managed to fix it by adding

`s.update();`

Into line 1950 of angular-ui-swiper.js

**Comment by emiliano1616** [comment]
Thanks Hyperblaster!
I wasn't able to try it untill now.
It works perfect.

**Comment by nebulr** [comment]
Thanks for the help!
