### ISSUE TITLE
breakpoints attribute error syntax

### ISSUE THREAD

**Issue by auban** [nebulr/ui-swiper#30]
Hello,

The breakpoints syntax is not same as angular. the json single make error with JSON.parse.
To solve the problem use $parse from angular.

example:
breakpoints="{'0':{'slidesPerView':1},'480':{'slidesPerView':2},'768':{'slidesPerView':3},'1025':{'slidesPerView':4}}"

Replace this s.params.breakpoints = JSON.parse(s.params.breakpoints);
With this s.params.breakpoints = $parse(s.params.breakpoints)();

**Comment by nebulr** [comment]
can you make a pull request?
