### ISSUE TITLE
compatible with angular 2+ ?

### ISSUE THREAD

**Issue by mehmetkose** [nebulr/ui-swiper#40]
I'm not really good at Angular world for now, and I just curious, is that module compatible with Angular 7?

**Comment by mehmetkose** [comment]
I think it is not

**Comment by AN602** [comment]
It is only compatible with angularJS. If you are looking for a Angular 7 module you can use [ngx-swiper-wrapper](https://github.com/zefoy/ngx-swiper-wrapper)
