### ISSUE TITLE
After Grunt build, swiper works in mobile but not in desktop

### ISSUE THREAD

**Issue by Duarte-Gomes** [nebulr/ui-swiper#7]
Hi,

After build the final project with grunt and upload it to my storage, the swiper doesn't work when checked in my pc. 
If using my phone the swiper is working.
The pagination dons't show and neither the swipe of the pages.

Thanks for the help.

**Comment by nebulr** [comment]
I'd have to see your build configuration. Post your grunt file.

**Comment by Duarte-Gomes** [comment]
Hi,
I was unable to get a fix so drop the swiper.
Thanks any way for the feedback.
